name: Publish
on:
  push:
    branches: [ feat/ci ]

jobs:
  publish:
    name: 'publish npm'
    runs-on: ubuntu-latest
    environment: npm
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
        working-directory: .
      - run: npm publish || true
        working-directory: .
        env:
          NODE_AUTH_TOKEN: 1dd19f81-7729-4fba-86ff-e0adfb55201d
